#!/usr/bin/env bash
#
# Starts the egress proxy, closes every other route out, then drops to the
# unprivileged `agent` user and execs the command.
#
# Every failure here exits non-zero. Running the agent with egress open would
# be worse than not running it, because `docs/enforced-where.md` claims this
# layer holds.
set -euo pipefail

: "${MANDATE_SQUID_CONF:?the config generated by compileEgress() must be passed}"

printf '%s\n' "$MANDATE_SQUID_CONF" > /etc/squid/squid.conf

# Fail with squid's own diagnostic rather than with a dead proxy. This is not a
# formality: a dstdomain ACL carrying both a domain and a subdomain of it is
# fatal, and whether it is fatal depends on their order.
squid -k parse -f /etc/squid/squid.conf

install -d -o proxy -g proxy -m 0755 /var/log/squid
squid -N -f /etc/squid/squid.conf &
squid_pid=$!

# Readiness by TCP connect. A check built on squidclient degrades into a plain
# sleep when that package is absent, which looks identical to a working check.
ready=0
for _ in $(seq 1 100); do
  if ! kill -0 "$squid_pid" 2>/dev/null; then
    echo "mandate-sandbox: squid exited during startup" >&2
    exit 1
  fi
  if (exec 3<>/dev/tcp/127.0.0.1/3128) 2>/dev/null; then ready=1; break; fi
  sleep 0.1
done
if [ "$ready" -ne 1 ]; then
  echo "mandate-sandbox: squid never accepted a connection on 3128" >&2
  exit 1
fi

# squid runs as `proxy` and cannot open root's /dev/stdout, so its access log is
# tailed here. Every allowed and denied egress attempt reaches the container's
# output, which is the audit record for traffic the action graph cannot see.
tail -F -n +1 /var/log/squid/access.log &

# The agent's only route out is the proxy.
#   - loopback first, so it can reach the proxy at all;
#   - squid keeps its own outbound access, because it runs as `proxy`;
#   - everything else from the agent uid is rejected, DNS included. With
#     HTTPS_PROXY set the proxy resolves names, so the agent never needs to,
#     and a direct resolver would be a channel of its own.
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner proxy -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner agent -j REJECT

exec setpriv --reuid=agent --regid=agent --clear-groups "$@"
