#!/usr/bin/env bash
#
# Starts the egress proxy, closes every other route out, then drops to the
# unprivileged `agent` user and execs the command.
#
# Every failure here exits non-zero. Running the agent with egress open would
# be worse than not running it, because `docs/enforced-where.md` claims this
# layer holds.
set -euo pipefail

: "${MANDATE_SQUID_CONF:?the config generated by compileEgress() must be passed}"

# The agent's channel to `mandate serve` on the host, when there is one. A
# target with no secret is refused: serve would refuse the relay anyway, and
# the agent would start with tools that silently never arrive.
relay_ip=""
relay_port=""
if [ -n "${MANDATE_RELAY_TARGET:-}" ]; then
  : "${MANDATE_RELAY_SECRET:?MANDATE_RELAY_TARGET is set but MANDATE_RELAY_SECRET is not}"
  relay_host="${MANDATE_RELAY_TARGET%:*}"
  relay_port="${MANDATE_RELAY_TARGET##*:}"
  if ! [[ "$relay_port" =~ ^[0-9]{1,5}$ ]]; then
    echo "mandate-sandbox: MANDATE_RELAY_TARGET has no usable port" >&2
    exit 1
  fi
  # Resolved now, as root, before the rules exist: the iptables hole is by
  # address, and neither uid that comes later has a resolver.
  relay_ip="$(getent ahostsv4 "$relay_host" | awk 'NR == 1 { print $1 }')"
  if [ -z "$relay_ip" ]; then
    echo "mandate-sandbox: cannot resolve $relay_host for the relay" >&2
    exit 1
  fi
  export MANDATE_RELAY_TARGET="$relay_ip:$relay_port"
fi

printf '%s\n' "$MANDATE_SQUID_CONF" > /etc/squid/squid.conf

# Fail with squid's own diagnostic rather than with a dead proxy. This is not a
# formality: a dstdomain ACL carrying both a domain and a subdomain of it is
# fatal, and whether it is fatal depends on their order.
squid -k parse -f /etc/squid/squid.conf

install -d -o proxy -g proxy -m 0755 /var/log/squid
squid -N -f /etc/squid/squid.conf &
squid_pid=$!

# Readiness by TCP connect. A check built on squidclient degrades into a plain
# sleep when that package is absent, which looks identical to a working check.
ready=0
for _ in $(seq 1 100); do
  if ! kill -0 "$squid_pid" 2>/dev/null; then
    echo "mandate-sandbox: squid exited during startup" >&2
    exit 1
  fi
  if (exec 3<>/dev/tcp/127.0.0.1/3128) 2>/dev/null; then ready=1; break; fi
  sleep 0.1
done
if [ "$ready" -ne 1 ]; then
  echo "mandate-sandbox: squid never accepted a connection on 3128" >&2
  exit 1
fi

# squid runs as `proxy` and cannot open root's /dev/stdout, so its access log is
# tailed here. Every allowed and denied egress attempt reaches the container's
# output, which is the audit record for traffic the action graph cannot see.
tail -F -n +1 /var/log/squid/access.log &

# The agent's only route out is the proxy.
#   - loopback first, so it can reach the proxy at all;
#   - squid keeps its own outbound access, because it runs as `proxy`;
#   - everything else from the agent uid is rejected, DNS included. With
#     HTTPS_PROXY set the proxy resolves names, so the agent never needs to,
#     and a direct resolver would be a channel of its own.
#
# The `proxy` ACCEPT is redundant while the OUTPUT policy is ACCEPT: the only
# REJECT names the agent uid. Verified by removing it, in both families, and
# watching squid still tunnel. It stays because it states the rule at the point
# it applies and becomes load-bearing the moment the policy is DROP.
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner proxy -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner agent -j REJECT

# The relay reaches serve's one port and nothing else. Its REJECT is not
# redundant the way the proxy ACCEPT is: the policy is ACCEPT, so without it
# the relay uid would have the open network the agent is denied.
if [ -n "$relay_ip" ]; then
  iptables -A OUTPUT -m owner --uid-owner relay -d "$relay_ip" -p tcp --dport "$relay_port" -j ACCEPT
fi
iptables -A OUTPUT -m owner --uid-owner relay -j REJECT

# The same rules over IPv6, because iptables covers IPv4 only. On a Docker
# network with IPv6 enabled the agent connected straight out over v6 while every
# IPv4 check reported blocked -- measured, not assumed.
#
# Guarded on the kernel having IPv6 at all: with no /proc/net/if_inet6 there is
# nothing to leak over, and refusing to start would only break hosts booted
# without it. Where IPv6 exists the rules must load, and `set -e` exits if they
# do not.
if [ -e /proc/net/if_inet6 ]; then
  ip6tables -A OUTPUT -o lo -j ACCEPT
  ip6tables -A OUTPUT -m owner --uid-owner proxy -j ACCEPT
  ip6tables -A OUTPUT -m owner --uid-owner agent -j REJECT
  ip6tables -A OUTPUT -m owner --uid-owner relay -j REJECT
fi

if [ -n "$relay_ip" ]; then
  install -d -o relay -g relay -m 0755 /run/mandate
  setpriv --reuid=relay --regid=relay --clear-groups \
    node /usr/local/lib/mandate-relay.mjs &
  relay_pid=$!
  ready=0
  for _ in $(seq 1 100); do
    if ! kill -0 "$relay_pid" 2>/dev/null; then
      echo "mandate-sandbox: the relay exited during startup" >&2
      exit 1
    fi
    if [ -S /run/mandate/mcp.sock ]; then ready=1; break; fi
    sleep 0.1
  done
  if [ "$ready" -ne 1 ]; then
    echo "mandate-sandbox: the relay never opened its socket" >&2
    exit 1
  fi
fi

# The workspace: `mandate run --sandbox` mounts a throwaway clone of HEAD here,
# read-only, and it is copied to a directory the agent owns. Never the
# operator's checkout, and never writable from the host side: a writable .git
# mounted in would let the agent plant a hook that the operator's own git runs
# on the host. On Docker Desktop a bind mount shows as root-owned, so the copy
# is also what lets the agent write at all.
if [ -d /mnt/mandate-workspace ]; then
  install -d -o agent -g agent -m 0755 /home/agent/workspace
  cp -a /mnt/mandate-workspace/. /home/agent/workspace/
  chown -R agent:agent /home/agent/workspace
  cd /home/agent/workspace
fi

# Belt: a well-behaved tool honours these. Braces: the iptables rules reject
# everything else from the agent uid, so a tool that ignores them fails at the
# network layer instead of reaching the internet. Set here rather than as image
# ENV, which would leak into the build steps of every image built FROM this one.
export HTTP_PROXY=http://127.0.0.1:3128 HTTPS_PROXY=http://127.0.0.1:3128
export http_proxy=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128
export NO_PROXY=127.0.0.1,localhost no_proxy=127.0.0.1,localhost

# The secret is the relay's, and the squid config is root's business. Neither
# goes to the agent. `env -u` names variables, so no value reaches any argv.
exec env -u MANDATE_RELAY_SECRET -u MANDATE_SQUID_CONF \
  setpriv --reuid=agent --regid=agent --clear-groups "$@"
